services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\PersonalizationBundle\Targeting\Maintenance\TargetingStorageTask: ~

    Pimcore\Bundle\PersonalizationBundle\Targeting\Service\TargetingEnableService: ~
